### ISSUE TITLE
Basic functionality

### ISSUE THREAD

**Issue by mwojtyna** [mwojtyna/lava-cms#18]
Can change the page title, description (meta tag) and language (html 'lang' attribute)

# Todo:

- [x] Dashboard with menu, header
- [x] Current path always shown (like in GitHub Projects)
- [x] Dark mode
- [x] User profile dropdown
- [x] #36 
- [x] Side menu (normal and nested links)
- [x] Settings page
- [x] Use SSR in Astro (Deno adapter cause node conflicts with pnpm) [deno-arm](https://github.com/LukeChannings/deno-arm64)
- [x] https://nextjs.org/docs/messages/sharp-missing-in-production
- [x] Tests
    - [x] ThemeSwitch
    - [x] UserMenu
    - [x] WebsiteSettings
