### ISSUE TITLE
First time setup wizard

### ISSUE THREAD

**Issue by mwojtyna** [mwojtyna/lava-cms#36]
# Todo:

- [x] second step of sign up page
- [x] inputs:
   - [x] website title (title tag)
   - [x] website description (meta tag)
   - [x] website language (html lang attribute)
   ~~- [ ] favicon~~
- [x] update firstTime trpc endpoint
- [x] additional info about inputs (question mark hover)
~~- [ ] transition between stages~~
