### ISSUE TITLE
Pages manager

### ISSUE THREAD

**Issue by mwojtyna** [mwojtyna/lava-cms#42]
# Description
A  list that allows to manage the website pages.

# Resources
https://ui.mantine.dev/category/dnd

# Todo:

- [x] Admin panel page
    - [x] figma
    - [x] default root page that can't be changed
    - [x] add page
    - [x] edit page
    - [x] remove page
    - [x] move page
    - [x] nested pages
    - [x] [AutoAnimate](https://auto-animate.formkit.com/)
    - [x] reorder pages
    - [x] collapse page children
    - [x] save folder open/close state
    - [x] lock slug editing
    - ~~[ ] bulk actions~~
- [x] Input validation
    - [x] convert name to slug
    - [x] prevent disallowed names (/admin)
- [x] Use in frontend
- [x] Tests
