### ISSUE TITLE
Page editor

### ISSUE THREAD

**Issue by mwojtyna** [mwojtyna/lava-cms#43]
# Description
 - Each page added in the pages menu.
 - The user is then responsible for editing the pages in his text editor.
 - The page editor is responsible for adding components to the page and configuring their content.

# Todo

- [x] page preview
- [x] add components dialog
- [x] components inspector
- [x] local state management, upload on save
- [x] add component
- [x] delete component
- [x] reorder components
- [x] connect changes to frontend
- [x] reload iframe on save
- [x] resize inspector
- [x] nested components
- [x] array fields editor
- [x] array fields sdk
- [x] less invasive way of disabling navigation in iframe
- [x] rollup -> vite
- [x] textarea field
- [x] fix astro imports
- [x] rich text field
- [x] handle adding field definitions when instances exist
- [x] handle editing component definition type
- [x] handle deleting component definitions when instances exist
- [x] animations
- [x] display nr of instances of component definition in its table, show more details in modal on click

# Resources
[Visual editor Storyblok](https://youtu.be/8aeGbBJn-wg?t=1257)
https://www.youtube.com/watch?v=ISoCH96q5Cs

## Rich text editor
 - [Slate](https://docs.slatejs.org/) + [Plate](https://platejs.org/)
 - https://www.storyblok.com/docs/richtext-field
