### ISSUE TITLE
Redo UI

### ISSUE THREAD

**Issue by mwojtyna** [mwojtyna/lava-cms#46]
# Description 
Make proper design in Figma

# Todo

- [x] Sign in form
- [x] Sign up form
- [x] Set up form
- [x] Nav menu
- [x] User menu
- [x] Settings
- [x] Pages (using DataTable component)
- [x] Tests

# Resources
https://ui.shadcn.com/
https://www.tremor.so/
https://tx.shadcn.com/dashboard
[Searchable Select](https://ui.shadcn.com/docs/components/command#combobox)
