### ISSUE TITLE
Page components

### ISSUE THREAD

**Issue by mwojtyna** [mwojtyna/lava-cms#54]
# Description
- Is created and its data types are defined in the dashboard
- In his code editor, user maps component name received by cms to a specific Astro component
- A special Astro component decides which component to render based on the data received by the cms and the map created by the user
- When a component is added to a page in the page editor, it is assigned an id. When the component is rendered on the page, a custom data attribute is added with the id. This allows us to pull up a window with the component properties when we click on it in the page editor.
- Render a fallback component with an error message when an Astro component hasn't been mapped to a cms component
- QOL: generate ts types when adding a component on the cms

# Todo

- [x] store component schemas in folders
- [x] create table in dashboard
- [x] dialogs for group
- [x] dialogs for component definition
- [x] bulk dialogs
- [x] handle adding a component definition with an existing name
- [x] fix no red border on error
- [x] tests

# Resources
## Bridge
https://docs.astro.build/en/reference/integrations-reference/
https://github.com/quicktype/quicktype
